---

- apt:
    update_cache: yes
    cache_valid_time: 36000
  become: yes

- apt:
    upgrade: yes
  become: yes

- apt:
    name: "{{ nginx_build_packages }}"
    state: latest
  become: yes

- apt:
    name: nginx
    state: build-dep
  become: yes

- command: id -u
  register: current_user_result

- set_fact: 
    current_user_id: "{{current_user_result.stdout}}"

- command: id -g
  register: current_group_result

- set_fact: 
    current_group_id: "{{current_group_result.stdout}}"

- set_fact: 
    build_root_dir: "/opt/src/nginx"

- file:
    path: "{{build_root_dir}}"
    state: directory
    mode: 0755
    owner: "{{ current_user_id }}"
    group: "{{ current_group_id }}"
  become: yes

- file:
    path: "{{ ccache_dir }}"
    state: directory
    mode: 0755
    owner: "{{ current_user_id }}"
    group: "{{ current_group_id }}"
  become: yes

- command: apt-get source nginx
  args:
    chdir: "{{build_root_dir}}"

- shell:  ls | egrep "^nginx-[0-9|\.]+$" | awk -F "-" '{print $2}'
  args:
    chdir: "{{build_root_dir}}"
  register: nginx_version_result

- set_fact:
    nginx_version: "{{nginx_version_result.stdout}}"

- set_fact:
    build_nginx_dir: "{{build_root_dir}}/nginx-{{nginx_version}}"

- set_fact:
    build_nginx_modules_dir: "{{build_root_dir}}/nginx_modules"

- file:
    path: "{{build_nginx_modules_dir}}"
    state: absent

- file:
    path: "{{build_nginx_modules_dir}}"
    state: directory
    mode: 0755

- include_tasks: module.yml
  vars:
    modules_path: "{{build_nginx_modules_dir}}"
  loop: "{{nginx_additional_modules}}"
  loop_control:
    loop_var: module

- lineinfile:
    path: "{{build_nginx_dir}}/debian/rules"
    regexp: '^(\s*)CFLAGS=(.+)LDFLAGS\)"(\s*)$'
    line: '     CFLAGS="" ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_dav_module --with-http_addition_module --with-http_auth_request_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_realip_module --add-module={{build_nginx_modules_dir}}/headers-more --add-module={{build_nginx_modules_dir}}/cache_purge --add-module={{build_nginx_modules_dir}}/devel_kit --add-module={{build_nginx_modules_dir}}/requestid  --add-module={{build_nginx_modules_dir}}/nginx-dav-ext-module  --with-cc-opt="$(CFLAGS)" --with-ld-opt="$(LDFLAGS)"'

- lineinfile:
    path: "{{build_nginx_dir}}/debian/changelog"
    insertbefore: BOF
    line: |
      nginx ({{nginx_version}}-1~akademiano~{{ansible_distribution_release}}) {{ansible_distribution_release}}; urgency=low

        * {{nginx_version}}

       -- {{nginx_build_user}} <{{nginx_build_user_email}}>  {{nginx_build_date}}

- name: compile nginx with modules
  shell: "export CCACHE_DIR=~/.ccache/; export CCACHE_PREFIX=icecc; export DEB_BUILD_OPTIONS='parallel={{ build_options_parallel }}'; debuild --preserve-envvar=CCACHE_DIR --preserve-envvar=CCACHE_PREFIX --prepend-path=/usr/lib/ccache -us -uc"
  args:
    executable: /bin/bash
    chdir: "{{build_nginx_dir}}"

- shell: 'ls | grep ".deb$" | grep -v "\-dbg"'
  args:
    executable: /bin/bash
    chdir: "{{build_root_dir}}"
  register: nginx_deb_result

- set_fact:
    nginx_deb: "{{build_root_dir}}/{{nginx_deb_result.stdout}}"

- name: install Nginx
  apt: 
    deb: "{{nginx_deb}}"
    state: present
  become: yes

- name: hold nginx package
  shell: apt-mark hold nginx
  args:
    executable: /bin/bash
  become: yes
